### PR TITLE
Don't cancel watch if an edit causes a compilation error

### LINKED ISSUE #1213: Importing a non-existing import should fail compilation
Or at least a separate check.

I assume this is not failing with babel because of per-file compilation, but possibly we can add an extra check.

CC @erwinmombay

### PR DESCRIPTION
**Pull request by rsimha-amp**
When `gulp watch` is running and an edit causes a compilation error, we currently cancel the `watch`. We should cancel on error during `gulp build` and the first build of `gulp | gulp watch`, but not when an edit causes a recompilation. See https://github.com/ampproject/amphtml/pull/13255#issuecomment-363546480

Follow up to #13255
Fixes #1213

### CODE REVIEW

**Comment by calebcordry** [comment]
@rsimha It seems like this is happening again. Any idea what changed?

**Comment by rsimha** [comment]
@calebcordry Pretty sure I caused this regression in #22659, particularly [this](https://github.com/ampproject/amphtml/pull/22659/files#diff-5dcccd952574ed97af51ac5c71b1c4f1R358) line >_<

Looking for a fix.
